# Generated by Django 4.2.2 on 2023-06-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_addsubtodoitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="addsubtodoitem",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
