# Generated by Django 4.2.2 on 2023-08-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0003_addsubtodoitem_content"),
    ]

    operations = [
        migrations.RenameModel(old_name="AddsubTodoItem", new_name="SubTodoItem",),
    ]
